// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/about.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/random-uuid.ts";
import * as $4 from "./routes/github/[username].tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/portfolio.tsx";
import * as $$0 from "./islands/ContactForm.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Footer.tsx";
import * as $$3 from "./islands/Header.tsx";
import * as $$4 from "./islands/NavMenu.tsx";
import * as $$5 from "./islands/PortfolioArt.tsx";
import * as $$6 from "./islands/PortfolioDev.tsx";
import * as $$7 from "./islands/PortfolioGameDev.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/about.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/random-uuid.ts": $3,
    "./routes/github/[username].tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/portfolio.tsx": $6,
  },
  islands: {
    "./islands/ContactForm.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Footer.tsx": $$2,
    "./islands/Header.tsx": $$3,
    "./islands/NavMenu.tsx": $$4,
    "./islands/PortfolioArt.tsx": $$5,
    "./islands/PortfolioDev.tsx": $$6,
    "./islands/PortfolioGameDev.tsx": $$7,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
